apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: chargeback-monitoring
spec:
  groups:
    - name: chargeback-monitoring.rules
      rules:
        - expr: >-
            sum by (label_${PROM_LABEL}) (container_memory_working_set_bytes{container="",pod!=""} * on (namespace) group_left(label_${PROM_LABEL}) kube_namespace_labels{label_${PROM_LABEL}=~".+"})
          record: '${PROM_LABEL}:container_memory_working_set_bytes:sum'
